version: "3"

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.10.2
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
  depends_on:
    - airflow_db

services:
  airflow_db:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5435:5432"
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  # ✅ Transactional Postgres (Source DB)
  pg_source:
    image: postgres:15
    environment:
      POSTGRES_USER: source_user
      POSTGRES_PASSWORD: source_pass
      POSTGRES_DB: source_db
    ports:
      - "5436:5432"
    volumes:
      - pg_source_data:/var/lib/postgresql/data

  # ✅ Analytical Postgres (Target DB)
  pg_analytics:
    image: postgres:15
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: analytics_db
    ports:
      - "5434:5432"
    volumes:
      - pg_analytics_data:/var/lib/postgresql/data

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    restart: always

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - airflow_db
      - pg_source
      - pg_analytics

volumes:
  postgres_airflow_data:
  pg_source_data:
  pg_analytics_data:
